apiVersion: apps/v1
kind: Deployment
metadata:
  name: catarse-db
spec:
  template:
    spec:
      containers:
        - name: catarse-db
          env:
            - name: POSTGRES_PASSWORD
              value: example
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: catarse-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catarse-moments-db
spec:
  template:
    spec:
      containers:
        - name: catarse-moments-db
          env:
            - name: POSTGRES_PASSWORD
              value: example
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: catarse-moments-data      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-core-db
spec:
  template:
    spec:
      containers:
        - name: service-core-db
          env:
            - name: POSTGRES_PASSWORD
              value: example
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: core-data
