apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: catarse-moments-db
  name: catarse-moments-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: catarse-moments-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: catarse_moments
        - name: POSTGRES_PASSWORD
          value: example
        - name: POSTGRES_USER
          value: postgres
        image: catarse-moments-db
        name: catarse-moments-db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-catarse-moments-data
      restartPolicy: Always
      volumes:
      - name: postgres-catarse-moments-data
        persistentVolumeClaim:
          claimName: postgres-catarse-moments-data
status: {}
