apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: catarse-migrations
  name: catarse-migrations
spec:
  containers:
  - args:
    - bundle
    - exec
    - rake
    - db:migrate
    env:
    - name: DATABASE_URL
      value: postgres://catarse:example@localhostcatarse:5432/catarse_db
    - name: RAILS_ENV
      value: development
    - name: REDIS_URL
      value: redis://catarse_redis:6379
    image: catarse-migrations
    name: catarse-migrations
    resources: {}
  restartPolicy: Never
status: {}
