apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: common-api
  name: common-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: common-api
    spec:
      containers:
      - args:
        - bundle
        - exec
        - rails
        - s
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: common-api-compose_env--common_api-env
        - name: GATEWAY_API_KEY
          valueFrom:
            configMapKeyRef:
              key: GATEWAY_API_KEY
              name: common-api-compose_env--common_api-env
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: JWT_SECRET
              name: common-api-compose_env--common_api-env
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: common-api-compose_env--common_api-env
        image: common-api
        name: common-api
        ports:
        - containerPort: 3000
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
