apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: common-api
  name: common-api
spec:
  ports:
  - name: "3014"
    port: 3014
    targetPort: 3000
  selector:
    io.kompose.service: common-api
status:
  loadBalancer: {}
