apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: hook-service-api
  name: hook-service-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: hook-service-api
    spec:
      containers:
      - args:
        - npm
        - start
        - server.js
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: hook-service-api-compose_env--hook_service_api-env
        - name: GATEWAY_API_KEY
          valueFrom:
            configMapKeyRef:
              key: GATEWAY_API_KEY
              name: hook-service-api-compose_env--hook_service_api-env
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: SENTRY_DSN
              name: hook-service-api-compose_env--hook_service_api-env
        image: hook-service-api
        name: hook-service-api
        ports:
        - containerPort: 4444
        resources: {}
      restartPolicy: Always
status: {}
