apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: migrations
  name: migrations
spec:
  containers:
  - args:
    - ./scripts/run_migrations.sh
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          key: DATABASE_URL
          name: migrations-compose_env--service_core_migrator-env
    image: migrations
    name: migrations
    resources: {}
  restartPolicy: Never
status: {}
