apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: project-service-api
  name: project-service-api
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 3000
  selector:
    io.kompose.service: project-service-api
status:
  loadBalancer: {}
