apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: read-api
  name: read-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: read-api
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: read-api-compose_env--read_api-env
        - name: PGRST_DB_ANON_ROLE
          valueFrom:
            configMapKeyRef:
              key: PGRST_DB_ANON_ROLE
              name: read-api-compose_env--read_api-env
        - name: PGRST_DB_POOL
          valueFrom:
            configMapKeyRef:
              key: PGRST_DB_POOL
              name: read-api-compose_env--read_api-env
        - name: PGRST_DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              key: PGRST_DB_SCHEMA
              name: read-api-compose_env--read_api-env
        - name: PGRST_DB_URI
          valueFrom:
            configMapKeyRef:
              key: PGRST_DB_URI
              name: read-api-compose_env--read_api-env
        - name: PGRST_JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: PGRST_JWT_SECRET
              name: read-api-compose_env--read_api-env
        - name: PGRST_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              key: PGRST_SERVER_HOST
              name: read-api-compose_env--read_api-env
        - name: PGRST_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: PGRST_SERVER_PORT
              name: read-api-compose_env--read_api-env
        - name: PGRST_SERVER_PROXY_URI
          valueFrom:
            configMapKeyRef:
              key: PGRST_SERVER_PROXY_URI
              name: read-api-compose_env--read_api-env
        - name: PROCESS_PAYMENT_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: PROCESS_PAYMENT_DATABASE_URL
              name: read-api-compose_env--read_api-env
        image: postgrest/postgrest:v5.2.0
        name: read-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
