apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: read-api
  name: read-api
spec:
  ports:
  - name: "3015"
    port: 3015
    targetPort: 3000
  selector:
    io.kompose.service: read-api
status:
  loadBalancer: {}
