apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: recommender-service-api
  name: recommender-service-api
spec:
  ports:
  - name: "3009"
    port: 3009
    targetPort: 3009
  selector:
    io.kompose.service: recommender-service-api
status:
  loadBalancer: {}
