apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: subscriptions-scheduler
  name: subscriptions-scheduler
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: subscriptions-scheduler
    spec:
      containers:
      - args:
        - ./scripts/subscription_scheduler.js
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: subscriptions-scheduler-compose_env--subscriptions_scheduler-env
        - name: SUBSCRIPTION_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: SUBSCRIPTION_INTERVAL
              name: subscriptions-scheduler-compose_env--subscriptions_scheduler-env
        image: subscriptions-scheduler
        name: subscriptions-scheduler
        resources: {}
      restartPolicy: Always
status: {}
