apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-service-api
  name: notification-service-api
spec:
  ports:
  - name: "3007"
    port: 3007
    targetPort: 3000
  selector:
    io.kompose.service: notification-service-api
status:
  loadBalancer: {}
