apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: catarse-db
  name: catarse-db
spec:
  ports:
  - port: 5432
  selector:
    io.kompose.service: catarse-db
status:
  loadBalancer: {}
